services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: claimchain
      POSTGRES_PASSWORD: claimchainpw
      POSTGRES_DB: claimchaindb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
