export type CreateClaimRequest = {
  debtorAddress: string;
  debtorType: string;
  jurisdictionState: string;
  claimType: string;
  disputeStatus: string;
  clientName: string;
  clientContact: string;
  clientAddress: string;
  debtType: string;
  contactHistory: string;
  currentAmount: number;
  dateOfDefault: string;
  debtorName?: string;
  debtorEmail?: string;
  debtorPhone?: string;
  originalAmount?: number;
  dateOfService?: string;
  lastPaymentDate?: string;
  contractFileKey?: string;
};

export type Claim = {
  id: string;
  debtorName?: string | null;
  debtorEmail?: string | null;
  debtorPhone?: string | null;
  debtorAddress: string;
  debtorType: string;
  jurisdictionState: string;
  claimType: string;
  disputeStatus: string;
  clientName: string;
  clientContact: string;
  clientAddress: string;
  debtType: string;
  contactHistory: string;
  originalAmount?: number | null;
  currentAmount?: number | null;
  amount?: number | null;
  dateOfDefault: string;
  dateOfService?: string | null;
  lastPaymentDate?: string | null;
  contractFileKey?: string | null;
  status?: string | null;
  submittedAt?: string | null;
  submittedBy?: string | null;
  scoreTotal?: number | null;
  grade?: string | null;
  extractionSuccessRate?: number | null;
  explainabilityJson?: string | null;
  scoreBreakdown?: string[] | null;
  scoringFactors?: string[] | null;
  subscoreEnforceability?: number | null;
  subscoreDocumentation?: number | null;
  subscoreCollectability?: number | null;
  subscoreOperationalRisk?: number | null;
};
