spring.application.name=ClaimChain

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/claimchaindb
spring.datasource.username=claimchain
spring.datasource.password=claimchainpw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always

# Server port (optional)
server.port=8080
